---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: openapi-merger-traefik-stripprefix
  namespace: alice
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /alice/api-docs
      - /alice/swagger
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: identity-service-traefik-stripprefix
  namespace: alice
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /alice/members
      - /alice/self
      - /alice/roles
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: attachment-api-traefik-stripprefix
  namespace: alice
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /alice/attachment
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: matchmaker-api-traefik-stripprefix
  namespace: alice
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /alice/demandA
      - /alice/demandB
      - /alice/match2
      - /alice/transaction
