# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
updateStrategy:
  type: Recreate
# ingressClass:
#   enabled: true
#   isDefaultClass: false
#   name: traefik
providers:
  kubernetesIngressNginx:
    enabled: true
    ingressClass: nginx
    watchIngressWithoutClass: true
    publishService:
      enabled: false
    publishStatusAddress: localhost
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
service:
  type: NodePort
# nodeSelector:
#   ingress-ready: "true"
#   kubernetes.io/os: linux
# tolerations:
#   - effect: NoSchedule
#     key: node-role.kubernetes.io/master
#     operator: Equal
#   - effect: NoSchedule
#     key: node-role.kubernetes.io/control-plane
#     operator: Equal
metrics:
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: monitoring
